// apps/wallpaper-module-web/src/views/login/index.vue
<template>
  <div class="login-container">
    <div class="login-box">
      <div class="login-left">
        <img src="@/assets/imgs/ikon.png" alt="login"/>
      </div>
      <div class="login-form">
        <div class="login-logo">
          <span class="logo-text">登录</span>
          <div class="underline"></div>
        </div>
        <el-form
          ref="loginFormRef"
          :model="loginForm"
          :rules="loginRules"
          @keyup.enter="handleLogin"
        >
          <el-form-item prop="username">
            <el-input
              v-model="loginForm.username"
              placeholder="请输入账号"
              :prefix-icon="User"
              maxlength="255"
            />
          </el-form-item>
          <el-form-item prop="password">
            <el-input
              v-model="loginForm.password"
              type="password"
              placeholder="请输入密码"
              :prefix-icon="Lock"
              maxlength="255"
              show-password
            />
          </el-form-item>
          <el-form-item prop="captcha">
            <el-space>
              <el-input v-model="loginForm.captchaCode" placeholder="请输入验证码"
                        :prefix-icon="Position"/>
              <img class="hand" :src="captchaImg" @click="generateCaptchaImg" alt="验证码"/>
            </el-space>
          </el-form-item>
          <el-form-item>
            <el-button
              :loading="loading"
              type="primary"
              @click="handleLogin"
              style="width: 100%"
            >
              登录
            </el-button>
          </el-form-item>
        </el-form>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import {ref, reactive, onMounted} from 'vue'
import {useRouter} from 'vue-router'
import {Base64} from 'js-base64'
import {ElMessage, FormInstance} from 'element-plus'

import {reqLogin, reqUserInfo} from '@/api/login/index.ts'
import {username, password, domain} from '../../../config'
import {User, Lock, Position} from "@element-plus/icons-vue";
import {v4 as uuidV4} from "uuid"


const router = useRouter()

const loginForm = reactive({
  username: username,
  password: password,
  captchaCode: "",
  captchaKey: ""
})

const loginRules = reactive({
  username: [{required: true, message: '请输入用户名', trigger: 'blur'}],
  password: [{required: true, message: '请输入密码', trigger: 'blur'}],
  // captcha: [{required: true, message: '请输入验证码', trigger: 'blur'}]
})

const captchaImg = ref("")


const loading = ref(false)
const loginFormRef = ref<FormInstance>()

// 登录处理
const handleLogin = () => {
  loginFormRef.value?.validate(async (valid) => {
    if (!valid) return

    loading.value = true

    const res = await reqLogin({
      ...loginForm,
      loginType: "teacher",
      loginDevice: "pc",
      password: Base64.encode(loginForm.password),
    })

    if (res.code === 200) {
      const {token} = res.data
      localStorage.setItem("token", token)
      ElMessage.success("登录成功")
    } else {
      generateCaptchaImg()
      ElMessage.error(res.msg)
    }
    loading.value = false
  })
}
const generateCaptchaImg = () => {
  loginForm.captchaKey = uuidV4()
  captchaImg.value = `${domain}/auth-api/auth/v1/captcha/${loginForm.captchaKey}?w=100&h=30`
}
// 如果已登录，直接跳转
onMounted(() => {
  generateCaptchaImg()
})
</script>

<style scoped lang="scss">
.login-container {
  position: relative;
  display: flex;
  align-items: center;
  justify-content: center;
  min-width: 550px;
  height: 100vh;
  min-height: 500px;
  background-color: #fff;

  .login-box {
    box-sizing: border-box;
    display: flex;
    align-items: center;
    width: 100%;
    height: 100%;
    overflow: hidden;
    border-radius: 10px;

    .login-left {
      display: flex;
      align-items: center;
      justify-content: center;
      width: 52%;
      height: 100%;
      padding: 0 100px;
      box-sizing: border-box;
      background: linear-gradient(
          180deg,
          rgba(14, 100, 244, 0.02) 0%,
          rgba(14, 100, 244, 0.08) 100%
      );

      img {
        width: 90%;
      }
    }

    .login-form {
      margin: auto;
      border-radius: 10px;

      .login-logo {
        width: 400px;
        display: flex;
        flex-direction: column;
        align-items: center;
        margin-bottom: 40px;

        .login-icon {
          width: 70px;
        }

        .logo-text {
          font-size: 40px;
          font-weight: bold;
          white-space: nowrap;
        }

        .underline {
          margin-top: 20px;
          width: 100px;
          height: 6px;
          background-color: #4187ff;
          border-radius: 6px;
        }
      }

      .ant-form-item {
        height: 75px;
        margin-bottom: 0;

        .ant-input-prefix {
          margin-right: 10px;
        }

        .ant-input-affix-wrapper-lg {
          padding: 8.3px 11px;
        }

        .ant-input-affix-wrapper,
        .ant-input-lg {
          font-size: 14px;
        }

        .ant-input-affix-wrapper {
          color: #aaa;
          background-color: #f5f5f5;
        }

        .ant-input {
          background-color: transparent !important;
        }
      }

      .login-btn {
        width: 100%;
        margin-top: 10px;

        .ant-form-item-control-input-content {
          .ant-btn {
            border-radius: 143px;
          }
        }
      }
    }
  }

}

</style>

// apps/backend-manage/src/views/login/index.tsx
import {useEffect, useState} from "react";
import {Button, Form, Input, message} from "antd";
import {LockOutlined, UserOutlined} from "@ant-design/icons";

import {v4 as uuidV4} from "uuid";

import {Navigate, useNavigate} from "react-router-dom";

import styles from "./index.module.scss";

import loginLeft from "@/assets/imgs/ikon.png";
import {reqLogin} from "@/api/login";
import {LoginInfoReq} from "@/api/login/types";
import {domain, password, username} from "@/config";

function Login() {
  const token = localStorage.getItem("backend-token");
  if (token) {
    return <Navigate to="/module" replace/>;
  }

  const navigate = useNavigate();
  const [form] = Form.useForm<LoginInfoReq>();
  const [loading, setLoading] = useState<boolean>(false);

  // 登录
  const onFinish = async (loginForm: LoginInfoReq) => {
    const params: LoginInfoReq = {
      loginType: "teacher",
      loginDevice: "pc",
      ...loginForm,
    };
    setLoading(true);
    const res = await reqLogin(params);
    if (res.code === 200) {
      const {token} = res.data;
      localStorage.setItem("backend-token", token);
      message.success("登录成功")
      navigate("/module");
    } else {
      message.error(res.msg);
    }
    setLoading(false);
  };
  const onFinishFailed = (errorInfo: any) => {
    console.error("Failed:", errorInfo);
  };
  const [captchaImg, setCaptchaImg] = useState("")
  const generateCaptchaImg = () => {
    const uuid = uuidV4()
    form.setFieldValue("captchaKey", uuid)
    setCaptchaImg(`${domain}/auth-api/v1/auth/captcha/${uuid}?w=100&h=30`)
  }
  useEffect(() => {
    generateCaptchaImg()
  }, [])
  return (
    <div className={styles.root}>
      <div className="login-box">
        <div className="login-left">
          <img src={loginLeft} alt="login"/>
        </div>
        <div className="login-form">
          <div className="login-logo">
            <span className="logo-text">后台管理</span>
            <div className="underline"></div>
          </div>
          <Form
            form={form}
            autoComplete="off"
            size="large"
            initialValues={{username: username, password: password}}
            onFinish={onFinish}
            onFinishFailed={onFinishFailed}>
            <Form.Item name="username" rules={[{required: true, message: "请输入用户名"}]}>
              <Input placeholder="请输入账号" prefix={<UserOutlined/>}/>
            </Form.Item>
            <Form.Item name="password" rules={[{required: true, message: "请输入密码"}]}>
              <Input.Password placeholder="请输入密码" prefix={<LockOutlined/>}/>
            </Form.Item>
            <Form.Item>
              <Form.Item name="captchaCode" rules={[{required: true, message: "请输入验证码"}]}
                         style={{display: 'inline-block', width: 'calc(50% - 8px)'}}>
                <Input placeholder="请输入验证码" prefix={<LockOutlined/>}/>
              </Form.Item>
              <img src={captchaImg} alt="验证码"
                   className="captcha-img"
                   onClick={generateCaptchaImg}
              />
            </Form.Item>
            <Form.Item name="captchaKey" hidden={true}>
              <div></div>
            </Form.Item>
            <Form.Item className="login-btn">
              <Button loading={loading} type="primary" htmlType="submit" block>
                登录
              </Button>
            </Form.Item>
          </Form>
        </div>
      </div>
    </div>
  );
}

export default Login;
